/***** File generated by ./internal/cmd/gobackends_ops_registration, based on github.com/gomlx/compute/. Don't edit it directly. *****/

package gobackend

import (
	"github.com/gomlx/compute"
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/shapes"
)

// Stub methods that converts compute.Value to *Node and dispatches to the corresponding op handler.
func (f *Function) DotGeneral(lhs compute.Value, lhsContractingAxes []int, lhsBatchAxes []int, rhs compute.Value, rhsContractingAxes []int, rhsBatchAxes []int, config compute.DotGeneralConfig) (compute.Value, error) {
	if RegisterDotGeneral.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.DotGeneral(lhs, lhsContractingAxes, lhsBatchAxes, rhs, rhsContractingAxes, rhsBatchAxes, config)
	}
	inputNodes, err := f.verifyAndCastValues("DotGeneral", lhs, rhs)
	if err != nil {
		return nil, err
	}
	nodeIdx := 0
	lhsNode := inputNodes[nodeIdx]
	nodeIdx++
	rhsNode := inputNodes[nodeIdx]
	nodeIdx++
	return RegisterDotGeneral.Fn(f, lhsNode, lhsContractingAxes, lhsBatchAxes, rhsNode, rhsContractingAxes, rhsBatchAxes, config)
}

func (f *Function) Iota(shape shapes.Shape, iotaAxis int) (compute.Value, error) {
	if RegisterIota.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Iota(shape, iotaAxis)
	}
	return RegisterIota.Fn(f, shape, iotaAxis)
}

// Registration variables for the op handlers.
var (
	RegisterDotGeneral = OpHandlerRegistration[func(f *Function, lhs *Node, lhsContractingAxes []int, lhsBatchAxes []int, rhs *Node, rhsContractingAxes []int, rhsBatchAxes []int, config compute.DotGeneralConfig) (*Node, error)]{
		Method: "DotGeneral",
	}
	RegisterIota = OpHandlerRegistration[func(f *Function, shape shapes.Shape, iotaAxis int) (*Node, error)]{
		Method: "Iota",
	}
)
