// Code generated by "enumer -type ScheduleStrategy -trimprefix=Schedule -output=gen_schedulestrategy_enumer.go schedule.go"; DO NOT EDIT.

package gobackend

import (
	"fmt"
	"strings"
)

const _ScheduleStrategyName = "CreationOrderScheduleDependencyOrderSchedule"

var _ScheduleStrategyIndex = [...]uint8{0, 21, 44}

const _ScheduleStrategyLowerName = "creationorderscheduledependencyorderschedule"

func (i ScheduleStrategy) String() string {
	if i < 0 || i >= ScheduleStrategy(len(_ScheduleStrategyIndex)-1) {
		return fmt.Sprintf("ScheduleStrategy(%d)", i)
	}
	return _ScheduleStrategyName[_ScheduleStrategyIndex[i]:_ScheduleStrategyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScheduleStrategyNoOp() {
	var x [1]struct{}
	_ = x[CreationOrderSchedule-(0)]
	_ = x[DependencyOrderSchedule-(1)]
}

var _ScheduleStrategyValues = []ScheduleStrategy{CreationOrderSchedule, DependencyOrderSchedule}

var _ScheduleStrategyNameToValueMap = map[string]ScheduleStrategy{
	_ScheduleStrategyName[0:21]:       CreationOrderSchedule,
	_ScheduleStrategyLowerName[0:21]:  CreationOrderSchedule,
	_ScheduleStrategyName[21:44]:      DependencyOrderSchedule,
	_ScheduleStrategyLowerName[21:44]: DependencyOrderSchedule,
}

var _ScheduleStrategyNames = []string{
	_ScheduleStrategyName[0:21],
	_ScheduleStrategyName[21:44],
}

// ScheduleStrategyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScheduleStrategyString(s string) (ScheduleStrategy, error) {
	if val, ok := _ScheduleStrategyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScheduleStrategyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ScheduleStrategy values", s)
}

// ScheduleStrategyValues returns all values of the enum
func ScheduleStrategyValues() []ScheduleStrategy {
	return _ScheduleStrategyValues
}

// ScheduleStrategyStrings returns a slice of all String values of the enum
func ScheduleStrategyStrings() []string {
	strs := make([]string, len(_ScheduleStrategyNames))
	copy(strs, _ScheduleStrategyNames)
	return strs
}

// IsAScheduleStrategy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ScheduleStrategy) IsAScheduleStrategy() bool {
	for _, v := range _ScheduleStrategyValues {
		if i == v {
			return true
		}
	}
	return false
}
