/***** File generated by ./internal/cmd/gobackends_ops_registration, based on github.com/gomlx/compute/. Don't edit it directly. *****/

package gobackend

import (
	"github.com/gomlx/compute"
	"github.com/gomlx/compute/shapes"
)

// Stub methods that converts compute.Value to *Node and dispatches to the corresponding op handler.
func (f *Function) BroadcastInDim(x compute.Value, outputShape shapes.Shape, broadcastAxes []int) (compute.Value, error) {
	if RegisterBroadcastInDim.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.BroadcastInDim(x, outputShape, broadcastAxes)
	}
	return RegisterBroadcastInDim.Fn(f, x, outputShape, broadcastAxes)
}

func (f *Function) DotGeneral(lhs compute.Value, lhsContractingAxes []int, lhsBatchAxes []int, rhs compute.Value, rhsContractingAxes []int, rhsBatchAxes []int, config compute.DotGeneralConfig) (compute.Value, error) {
	if RegisterDotGeneral.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.DotGeneral(lhs, lhsContractingAxes, lhsBatchAxes, rhs, rhsContractingAxes, rhsBatchAxes, config)
	}
	return RegisterDotGeneral.Fn(f, lhs, lhsContractingAxes, lhsBatchAxes, rhs, rhsContractingAxes, rhsBatchAxes, config)
}

func (f *Function) FusedAttentionQKVProjection(x compute.Value, wQKV compute.Value, biasQ compute.Value, biasK compute.Value, biasV compute.Value, queryDim int, keyValueDim int) (query compute.Value, key compute.Value, value compute.Value, err error) {
	if RegisterFusedAttentionQKVProjection.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedAttentionQKVProjection(x, wQKV, biasQ, biasK, biasV, queryDim, keyValueDim)
	}
	return RegisterFusedAttentionQKVProjection.Fn(f, x, wQKV, biasQ, biasK, biasV, queryDim, keyValueDim)
}

func (f *Function) FusedDense(x compute.Value, weight compute.Value, bias compute.Value, activation compute.ActivationType) (compute.Value, error) {
	if RegisterFusedDense.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedDense(x, weight, bias, activation)
	}
	return RegisterFusedDense.Fn(f, x, weight, bias, activation)
}

func (f *Function) FusedGelu(x compute.Value, exact bool) (compute.Value, error) {
	if RegisterFusedGelu.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedGelu(x, exact)
	}
	return RegisterFusedGelu.Fn(f, x, exact)
}

func (f *Function) FusedLayerNorm(x compute.Value, axes []int, epsilon float64, gamma compute.Value, beta compute.Value) (compute.Value, error) {
	if RegisterFusedLayerNorm.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedLayerNorm(x, axes, epsilon, gamma, beta)
	}
	return RegisterFusedLayerNorm.Fn(f, x, axes, epsilon, gamma, beta)
}

func (f *Function) FusedQuantizedDense(x compute.Value, weights compute.Value, bias compute.Value, weightsQuantization *compute.Quantization, activation compute.ActivationType) (compute.Value, error) {
	if RegisterFusedQuantizedDense.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedQuantizedDense(x, weights, bias, weightsQuantization, activation)
	}
	return RegisterFusedQuantizedDense.Fn(f, x, weights, bias, weightsQuantization, activation)
}

func (f *Function) FusedScaledDotProductAttention(query compute.Value, key compute.Value, value compute.Value, mask compute.Value, numHeads int, numKVHeads int, axesLayout compute.AxesLayout, scale float64, causal bool, options *compute.ScaledDotProductAttentionConfig) (compute.Value, error) {
	if RegisterFusedScaledDotProductAttention.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedScaledDotProductAttention(query, key, value, mask, numHeads, numKVHeads, axesLayout, scale, causal, options)
	}
	return RegisterFusedScaledDotProductAttention.Fn(f, query, key, value, mask, numHeads, numKVHeads, axesLayout, scale, causal, options)
}

func (f *Function) FusedSoftmax(x compute.Value, axis int) (compute.Value, error) {
	if RegisterFusedSoftmax.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.FusedSoftmax(x, axis)
	}
	return RegisterFusedSoftmax.Fn(f, x, axis)
}

func (f *Function) Gather(operand compute.Value, startIndices compute.Value, indexVectorAxis int, offsetOutputAxes []int, collapsedSliceAxes []int, startIndexMap []int, sliceSizes []int, indicesAreSorted bool) (compute.Value, error) {
	if RegisterGather.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Gather(operand, startIndices, indexVectorAxis, offsetOutputAxes, collapsedSliceAxes, startIndexMap, sliceSizes, indicesAreSorted)
	}
	return RegisterGather.Fn(f, operand, startIndices, indexVectorAxis, offsetOutputAxes, collapsedSliceAxes, startIndexMap, sliceSizes, indicesAreSorted)
}

func (f *Function) Iota(shape shapes.Shape, iotaAxis int) (compute.Value, error) {
	if RegisterIota.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Iota(shape, iotaAxis)
	}
	return RegisterIota.Fn(f, shape, iotaAxis)
}

func (f *Function) QuantizedEmbeddingLookup(data compute.Value, indices compute.Value, dataQuantization *compute.Quantization) (compute.Value, error) {
	if RegisterQuantizedEmbeddingLookup.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.QuantizedEmbeddingLookup(data, indices, dataQuantization)
	}
	return RegisterQuantizedEmbeddingLookup.Fn(f, data, indices, dataQuantization)
}

func (f *Function) ReduceBitwiseAnd(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceBitwiseAnd.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceBitwiseAnd(x, axes...)
	}
	return RegisterReduceBitwiseAnd.Fn(f, x, axes...)
}

func (f *Function) ReduceBitwiseOr(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceBitwiseOr.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceBitwiseOr(x, axes...)
	}
	return RegisterReduceBitwiseOr.Fn(f, x, axes...)
}

func (f *Function) ReduceBitwiseXor(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceBitwiseXor.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceBitwiseXor(x, axes...)
	}
	return RegisterReduceBitwiseXor.Fn(f, x, axes...)
}

func (f *Function) ReduceLogicalAnd(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceLogicalAnd.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceLogicalAnd(x, axes...)
	}
	return RegisterReduceLogicalAnd.Fn(f, x, axes...)
}

func (f *Function) ReduceLogicalOr(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceLogicalOr.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceLogicalOr(x, axes...)
	}
	return RegisterReduceLogicalOr.Fn(f, x, axes...)
}

func (f *Function) ReduceLogicalXor(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceLogicalXor.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceLogicalXor(x, axes...)
	}
	return RegisterReduceLogicalXor.Fn(f, x, axes...)
}

func (f *Function) ReduceMax(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceMax.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceMax(x, axes...)
	}
	return RegisterReduceMax.Fn(f, x, axes...)
}

func (f *Function) ReduceMin(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceMin.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceMin(x, axes...)
	}
	return RegisterReduceMin.Fn(f, x, axes...)
}

func (f *Function) ReduceProduct(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceProduct.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceProduct(x, axes...)
	}
	return RegisterReduceProduct.Fn(f, x, axes...)
}

func (f *Function) ReduceSum(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReduceSum.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.ReduceSum(x, axes...)
	}
	return RegisterReduceSum.Fn(f, x, axes...)
}

func (f *Function) Reshape(x compute.Value, dimensions ...int) (compute.Value, error) {
	if RegisterReshape.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Reshape(x, dimensions...)
	}
	return RegisterReshape.Fn(f, x, dimensions...)
}

func (f *Function) Reverse(x compute.Value, axes ...int) (compute.Value, error) {
	if RegisterReverse.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Reverse(x, axes...)
	}
	return RegisterReverse.Fn(f, x, axes...)
}

func (f *Function) Transpose(x compute.Value, permutation ...int) (compute.Value, error) {
	if RegisterTranspose.Fn == nil {
		// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.
		return f.Function.Transpose(x, permutation...)
	}
	return RegisterTranspose.Fn(f, x, permutation...)
}

// Registration variables for the op handlers.
var (
	RegisterBroadcastInDim = OpHandlerRegistration[func(f *Function, x compute.Value, outputShape shapes.Shape, broadcastAxes []int) (compute.Value, error)]{
		Method: "BroadcastInDim",
	}
	RegisterDotGeneral = OpHandlerRegistration[func(f *Function, lhs compute.Value, lhsContractingAxes []int, lhsBatchAxes []int, rhs compute.Value, rhsContractingAxes []int, rhsBatchAxes []int, config compute.DotGeneralConfig) (compute.Value, error)]{
		Method: "DotGeneral",
	}
	RegisterFusedAttentionQKVProjection = OpHandlerRegistration[func(f *Function, x compute.Value, wQKV compute.Value, biasQ compute.Value, biasK compute.Value, biasV compute.Value, queryDim int, keyValueDim int) (query compute.Value, key compute.Value, value compute.Value, err error)]{
		Method: "FusedAttentionQKVProjection",
	}
	RegisterFusedDense = OpHandlerRegistration[func(f *Function, x compute.Value, weight compute.Value, bias compute.Value, activation compute.ActivationType) (compute.Value, error)]{
		Method: "FusedDense",
	}
	RegisterFusedGelu = OpHandlerRegistration[func(f *Function, x compute.Value, exact bool) (compute.Value, error)]{
		Method: "FusedGelu",
	}
	RegisterFusedLayerNorm = OpHandlerRegistration[func(f *Function, x compute.Value, axes []int, epsilon float64, gamma compute.Value, beta compute.Value) (compute.Value, error)]{
		Method: "FusedLayerNorm",
	}
	RegisterFusedQuantizedDense = OpHandlerRegistration[func(f *Function, x compute.Value, weights compute.Value, bias compute.Value, weightsQuantization *compute.Quantization, activation compute.ActivationType) (compute.Value, error)]{
		Method: "FusedQuantizedDense",
	}
	RegisterFusedScaledDotProductAttention = OpHandlerRegistration[func(f *Function, query compute.Value, key compute.Value, value compute.Value, mask compute.Value, numHeads int, numKVHeads int, axesLayout compute.AxesLayout, scale float64, causal bool, options *compute.ScaledDotProductAttentionConfig) (compute.Value, error)]{
		Method: "FusedScaledDotProductAttention",
	}
	RegisterFusedSoftmax = OpHandlerRegistration[func(f *Function, x compute.Value, axis int) (compute.Value, error)]{
		Method: "FusedSoftmax",
	}
	RegisterGather = OpHandlerRegistration[func(f *Function, operand compute.Value, startIndices compute.Value, indexVectorAxis int, offsetOutputAxes []int, collapsedSliceAxes []int, startIndexMap []int, sliceSizes []int, indicesAreSorted bool) (compute.Value, error)]{
		Method: "Gather",
	}
	RegisterIota = OpHandlerRegistration[func(f *Function, shape shapes.Shape, iotaAxis int) (compute.Value, error)]{
		Method: "Iota",
	}
	RegisterQuantizedEmbeddingLookup = OpHandlerRegistration[func(f *Function, data compute.Value, indices compute.Value, dataQuantization *compute.Quantization) (compute.Value, error)]{
		Method: "QuantizedEmbeddingLookup",
	}
	RegisterReduceBitwiseAnd = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceBitwiseAnd",
	}
	RegisterReduceBitwiseOr = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceBitwiseOr",
	}
	RegisterReduceBitwiseXor = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceBitwiseXor",
	}
	RegisterReduceLogicalAnd = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceLogicalAnd",
	}
	RegisterReduceLogicalOr = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceLogicalOr",
	}
	RegisterReduceLogicalXor = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceLogicalXor",
	}
	RegisterReduceMax = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceMax",
	}
	RegisterReduceMin = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceMin",
	}
	RegisterReduceProduct = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceProduct",
	}
	RegisterReduceSum = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "ReduceSum",
	}
	RegisterReshape = OpHandlerRegistration[func(f *Function, x compute.Value, dimensions ...int) (compute.Value, error)]{
		Method: "Reshape",
	}
	RegisterReverse = OpHandlerRegistration[func(f *Function, x compute.Value, axes ...int) (compute.Value, error)]{
		Method: "Reverse",
	}
	RegisterTranspose = OpHandlerRegistration[func(f *Function, x compute.Value, permutation ...int) (compute.Value, error)]{
		Method: "Transpose",
	}
)
