// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"os/exec"
	"path"
	"slices"
	"strings"
	"text/template"

	"fmt"

	"github.com/gomlx/compute/internal/must"
	"github.com/gomlx/compute/support/backendparser"
	"github.com/gomlx/compute/support/sets"
	"k8s.io/klog/v2"
)

const (
	opsRegistrationFile = "gen_opsregistration.go"
)

var (
	// methodsExcluded from generating and even from having a NodeType.
	// These are utility methods, not part of building a graph.
	methodsExcluded = sets.MakeWith(
		"Name", "Compile", "OpShape", "Main", "NewFunction",
		"Return", "Closure", "Name",
		"DistributedSPMD", "DistributedAutoSharding", "DeviceAssignment")

	// methodsIncluded from StandardOps for which we want to generate and register stub methods.
	// Temporary: until we refactored them all.
	methodsIncluded = sets.MakeWith("Iota", "DotGeneral", "BroadcastInDim", "Gather", "Reshape", "Reverse", "Transpose")

	opsRegistrationTemplate = template.Must(template.New(opsRegistrationFile).Parse(
		`/***** File generated by ./internal/cmd/gobackends_ops_registration, based on github.com/gomlx/compute/. Don't edit it directly. *****/

package gobackend

import (
	"github.com/gomlx/compute"
	"github.com/gomlx/compute/shapes"
)

// Stub methods that converts compute.Value to *Node and dispatches to the corresponding op handler.
{{- range .}}
{{.StubFunction}}

{{- end}}


// Registration variables for the op handlers.
var (
{{- range .}}
	Register{{.Name}} = OpHandlerRegistration[{{.HandlerSignature}}]{
		Method: "{{.Name}}",
	}
{{- end}}
)

`))
)

// MethodEntry used as input to the template.
type MethodEntry struct {
	backendparser.Method
	HandlerSignature string
	StubFunction     string // Complete stub function for the standard method.
}

// GenerateOpsRegistration generates a registration system for each of the compute.StandardOps methods, so they can be
// implemented separated by separate packages, as well as stub methods for `gobackends.Backend` that calls the
// corresponding registered method if configured.
func GenerateOpsRegistration(methods []backendparser.Method) {
	methodsForTemplate := make([]MethodEntry, 0, len(methods))
	for _, method := range methods {
		if method.Interface != "StandardOps" {
			// Only generating for StandardOps for now.
			continue
		}
		if methodsExcluded.Has(method.Name) {
			continue
		}
		if len(methodsIncluded) > 0 && !methodsIncluded.Has(method.Name) {
			continue
		}
		if len(method.Outputs) != 2 || method.Outputs[0].Type != "Value" || method.Outputs[1].Type != "error" {
			// Non-conventional op, skipping.
			continue
		}
		methodEntry := MethodEntry{
			Method: method,
		}
		normalizeParameterTypes(&methodEntry.Method)
		generateHandlerSignature(&methodEntry)
		generateStubFunction(&methodEntry)
		methodsForTemplate = append(methodsForTemplate, methodEntry)
	}
	slices.SortFunc(methodsForTemplate, func(a, b MethodEntry) int { return strings.Compare(a.Name, b.Name) })

	fileName := path.Join(must.M1(os.Getwd()), opsRegistrationFile)
	f := must.M1(os.Create(fileName))
	must.M(opsRegistrationTemplate.Execute(f, methodsForTemplate))
	cmd := exec.Command("go", "fmt", fileName)
	cmd.Stderr = os.Stderr
	klog.V(1).Infof("\t%s\n", cmd)
	if err := cmd.Run(); err != nil {
		klog.Fatalf("Command [%s] failed: %v", cmd, err)
	}
	fmt.Printf("✅ gobackend_opsregistration:\tsuccessfully generated %s\n", fileName)
}

// normalizeParameterTypes adds the `compute.` package prefix to the corresponding parameter types.
func normalizeParameterTypes(method *backendparser.Method) {
	for i := range method.Parameters {
		param := &method.Parameters[i]
		switch param.Type {
		case "Value":
			param.Type = "compute.Value"
		case "...Value":
			param.Type = "...compute.Value"
		case "[]Value":
			param.Type = "[]compute.Value"
		case "Shape":
			param.Type = "shapes.Shape"
		case "ReduceOpType":
			param.Type = "compute.ReduceOpType"
		case "FFTType":
			param.Type = "compute.FFTType"
		case "ConvolveAxesConfig":
			param.Type = "compute.ConvolveAxesConfig"
		case "...PadAxis":
			param.Type = "...compute.PadAxis"
		case "ActivationType":
			param.Type = "compute.ActivationType"
		case "AxesLayout":
			param.Type = "compute.AxesLayout"
		case "QuantizationScheme":
			param.Type = "compute.QuantizationScheme"
		case "DotGeneralConfig":
			param.Type = "compute.DotGeneralConfig"
		case "*Quantization":
			param.Type = "*compute.Quantization"
		case "*ScaledDotProductAttentionConfig":
			param.Type = "*compute.ScaledDotProductAttentionConfig"
		}
	}
}

// generateHandlerSignature creates the Go backend handler function signature for the method.
func generateHandlerSignature(method *MethodEntry) {
	var sigBuf strings.Builder
	w := func(s string, args ...any) {
		sigBuf.WriteString(fmt.Sprintf(s, args...))
	}
	w("func(f *Function")
	for _, param := range method.Parameters {
		w(", ")
		switch param.Type {
		case "compute.Value":
			param.Type = "*Node"
		case "...compute.Value":
			param.Type = "...*Node"
		case "[]compute.Value":
			param.Type = "[]*Node"
		}
		w("%s %s", param.Name, param.Type)
	}
	w(") ")
	if len(method.Outputs) > 1 || method.Outputs[0].Name != "" {
		w("(")
	}
	for i, output := range method.Outputs {
		switch output.Type {
		case "Value":
			output.Type = "*Node"
		case "...Value":
			output.Type = "...*Node"
		case "[]Value":
			output.Type = "[]*Node"
		}
		if i > 0 {
			w(", ")
		}
		if output.Name != "" {
			w("%s ", output.Name)
		}
		w("%s", output.Type)
	}
	if len(method.Outputs) > 1 || method.Outputs[0].Name != "" {
		w(")")
	}
	method.HandlerSignature = sigBuf.String()
}

// generateStubFunction creates the Go stub function for the method.
func generateStubFunction(method *MethodEntry) {
	var wBuf strings.Builder
	w := func(s string, args ...any) {
		wBuf.WriteString(fmt.Sprintf(s, args...))
	}

	w("func (f *Function) %s(", method.Name)
	for i, param := range method.Parameters {
		if i > 0 {
			w(", ")
		}
		w("%s %s", param.Name, param.Type)
	}
	w(") (compute.Value, error) {\n")

	w("\tif Register%s.Fn == nil {\n", method.Name)
	w("\t\t// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.\n")
	w("\t\treturn f.Function.%s(", method.Name)
	for i, param := range method.Parameters {
		if i > 0 {
			w(", ")
		}
		if strings.HasPrefix(param.Type, "...") {
			w("%s...", param.Name)
		} else {
			w("%s", param.Name)
		}
	}
	w(")\n\t}\n")

	var valParams []backendparser.NameAndType
	for _, param := range method.Parameters {
		if param.Type == "compute.Value" || param.Type == "...compute.Value" || param.Type == "[]compute.Value" {
			valParams = append(valParams, param)
		}
	}

	if len(valParams) > 0 {
		w("\tinputNodes, err := f.verifyAndCastValues(\"%s\"", method.Name)
		for _, param := range valParams {
			switch param.Type {
			case "compute.Value":
				w(", %s", param.Name)
			case "...compute.Value":
				w(", %s...", param.Name)
			case "[]compute.Value":
				w(", %s...", param.Name)
			}
		}
		w(")\n")
		w("\tif err != nil {\n")
		w("\t\treturn nil, err\n")
		w("\t}\n")

		w("\tnodeIdx := 0\n")
		for _, param := range method.Parameters {
			switch param.Type {
			case "compute.Value":
				w("\t%sNode := inputNodes[nodeIdx]\n", param.Name)
				w("\tnodeIdx++\n")
			case "...compute.Value":
				w("\t%sNode := inputNodes[nodeIdx:]\n", param.Name)
			case "[]compute.Value":
				w("\t%sNode := inputNodes[nodeIdx : nodeIdx+len(%s)]\n", param.Name, param.Name)
				w("\tnodeIdx += len(%s)\n", param.Name)
			}
		}
	}

	w("\treturn Register%s.Fn(f", method.Name)
	for _, param := range method.Parameters {
		if param.Type == "compute.Value" || param.Type == "...compute.Value" || param.Type == "[]compute.Value" {
			w(", %sNode", param.Name)
			if param.Type == "...compute.Value" {
				w("...")
			}
		} else {
			w(", %s", param.Name)
			if strings.HasPrefix(param.Type, "...") {
				w("...")
			}
		}
	}
	w(")\n")
	w("}\n")
	method.StubFunction = wBuf.String()
}
