// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"os/exec"
	"path"
	"slices"
	"strings"
	"text/template"

	"fmt"

	"github.com/gomlx/compute/internal/must"
	"github.com/gomlx/compute/support/backendparser"
	"github.com/gomlx/compute/support/sets"
	"k8s.io/klog/v2"
)

const (
	opsRegistrationFile = "gen_opsregistration.go"
)

var (
	// methodsExcluded from generating and even from having a NodeType.
	// These are utility methods, not part of building a graph.
	methodsExcluded = sets.MakeWith(
		"Name", "Compile", "OpShape", "Main", "NewFunction",
		"Return", "Closure", "Name",
		"DistributedSPMD", "DistributedAutoSharding", "DeviceAssignment")

	// methodsIncluded from StandardOps for which we want to generate and register stub methods.
	// Temporary: until we refactored them all.
	//
	// Note: All FusedOps are already included.
	methodsIncluded = sets.MakeWith("Iota", "DotGeneral", "BroadcastInDim", "Gather", "Reshape", "Reverse", "Transpose",
		"ReduceMax", "ReduceMin", "ReduceSum", "ReduceProduct",
		"ReduceBitwiseAnd", "ReduceBitwiseOr", "ReduceBitwiseXor",
		"ReduceLogicalAnd", "ReduceLogicalOr", "ReduceLogicalXor",
		"ConvGeneral",

		// Binary Operations:
		"Add", "Mul", "Sub", "Div", "Rem", "Pow", "Atan2", "BitwiseAnd", "BitwiseOr", "BitwiseXor", "ShiftLeft",
		"ShiftRightArithmetic", "ShiftRightLogical", "LogicalAnd", "LogicalOr", "LogicalXor", "Max", "Min", "Equal",
		"NotEqual", "GreaterOrEqual", "GreaterThan", "LessOrEqual", "LessThan",

		// Unary Operations:
		"Neg", "Abs", "Sign", "LogicalNot", "BitwiseNot", "BitCount", "Clz", "Exp", "Expm1", "Log", "Log1p", "Ceil",
		"Floor", "Round", "Rsqrt", "Sqrt", "Cos", "Sin", "Tanh", "IsFinite", "Logistic", "Erf",

		// Control Flow:
		"Call", "If", "While", "Sort",
	)

	opsRegistrationTemplate = template.Must(template.New(opsRegistrationFile).Parse(
		`/***** File generated by ./internal/cmd/gobackends_ops_registration, based on github.com/gomlx/compute/. Don't edit it directly. *****/

package gobackend

import (
	"github.com/gomlx/compute"
	"github.com/gomlx/compute/shapes"
)

// Stub methods that converts compute.Value to *Node and dispatches to the corresponding op handler.
{{- range .}}
{{.StubFunction}}

{{- end}}


// Registration variables for the op handlers.
var (
{{- range .}}
	Register{{.Name}} = OpHandlerRegistration[{{.HandlerSignature}}]{
		Method: "{{.Name}}",
	}
{{- end}}
)

`))
)

// MethodEntry used as input to the template.
type MethodEntry struct {
	backendparser.Method
	HandlerSignature string
	StubFunction     string // Complete stub function for the standard method.
}

// GenerateOpsRegistration generates a registration system for each of the compute.StandardOps methods, so they can be
// implemented separated by separate packages, as well as stub methods for `gobackends.Backend` that calls the
// corresponding registered method if configured.
func GenerateOpsRegistration(methods []backendparser.Method) {
	methodsForTemplate := make([]MethodEntry, 0, len(methods))
	for _, method := range methods {
		if methodsExcluded.Has(method.Name) {
			continue
		}
		// All FusedOps are included.
		if !methodsIncluded.Has(method.Name) && method.Interface != "FusedOps" {
			continue
		}
		methodEntry := MethodEntry{
			Method: method,
		}
		normalizeParameterTypes(&methodEntry.Method)
		generateHandlerSignature(&methodEntry)
		generateStubFunction(&methodEntry)
		methodsForTemplate = append(methodsForTemplate, methodEntry)
	}
	slices.SortFunc(methodsForTemplate, func(a, b MethodEntry) int {
		return strings.Compare(strings.ToUpper(a.Name), strings.ToUpper(b.Name))
	})

	fileName := path.Join(must.M1(os.Getwd()), opsRegistrationFile)
	f := must.M1(os.Create(fileName))
	must.M(opsRegistrationTemplate.Execute(f, methodsForTemplate))
	cmd := exec.Command("go", "fmt", fileName)
	cmd.Stderr = os.Stderr
	klog.V(1).Infof("\t%s\n", cmd)
	if err := cmd.Run(); err != nil {
		klog.Fatalf("Command [%s] failed: %v", cmd, err)
	}
	fmt.Printf("✅ gobackend_opsregistration:\tsuccessfully generated %s\n", fileName)
}

// normalizeParameterTypes adds the `compute.` package prefix to the corresponding parameter types.
func normalizeParameterTypes(method *backendparser.Method) {
	for _, paramSet := range []*[]backendparser.NameAndType{&method.Parameters, &method.Outputs} {
		for i := range *paramSet {
			param := &(*paramSet)[i]
			if param.Name == "f" {
				// Rename the 'f' parameter to 'fn' to avoid conflict with the receiver name 'f'.
				param.Name = "fn"
			}
			switch param.Type {
			case "Value":
				param.Type = "compute.Value"
			case "...Value":
				param.Type = "...compute.Value"
			case "[]Value":
				param.Type = "[]compute.Value"
			case "Shape":
				param.Type = "shapes.Shape"
			case "Function":
				param.Type = "compute.Function"
			case "ReduceOpType":
				param.Type = "compute.ReduceOpType"
			case "FFTType":
				param.Type = "compute.FFTType"
			case "ConvolveAxesConfig":
				param.Type = "compute.ConvolveAxesConfig"
			case "...PadAxis":
				param.Type = "...compute.PadAxis"
			case "ActivationType":
				param.Type = "compute.ActivationType"
			case "AxesLayout":
				param.Type = "compute.AxesLayout"
			case "QuantizationScheme":
				param.Type = "compute.QuantizationScheme"
			case "DotGeneralConfig":
				param.Type = "compute.DotGeneralConfig"
			case "*Quantization":
				param.Type = "*compute.Quantization"
			case "*ScaledDotProductAttentionConfig":
				param.Type = "*compute.ScaledDotProductAttentionConfig"
			}
		}
	}
}

// generateHandlerSignature creates the Go backend handler function signature for the method.
func generateHandlerSignature(method *MethodEntry) {
	var sigBuf strings.Builder
	w := func(s string, args ...any) {
		sigBuf.WriteString(fmt.Sprintf(s, args...))
	}
	w("func(f *Function")
	for _, param := range method.Parameters {
		w(", ")
		w("%s %s", param.Name, param.Type)
	}
	w(") ")
	if len(method.Outputs) > 1 || method.Outputs[0].Name != "" {
		w("(")
	}
	for i, output := range method.Outputs {
		switch output.Type {
		case "Value":
			output.Type = "compute.Value"
		case "...Value":
			output.Type = "...compute.Value"
		case "[]Value":
			output.Type = "[]compute.Value"
		}
		if i > 0 {
			w(", ")
		}
		if output.Name != "" {
			w("%s ", output.Name)
		}
		w("%s", output.Type)
	}
	if len(method.Outputs) > 1 || method.Outputs[0].Name != "" {
		w(")")
	}
	method.HandlerSignature = sigBuf.String()
}

// generateStubFunction creates the Go stub function for the method.
func generateStubFunction(method *MethodEntry) {
	var wBuf strings.Builder
	w := func(s string, args ...any) {
		wBuf.WriteString(fmt.Sprintf(s, args...))
	}

	w("func (f *Function) %s(", method.Name)
	for i, param := range method.Parameters {
		if i > 0 {
			w(", ")
		}
		w("%s %s", param.Name, param.Type)
	}
	w(") (")
	for i, output := range method.Outputs {
		if i > 0 {
			w(", ")
		}
		w("%s %s", output.Name, output.Type)
	}
	w(") {\n")

	w("\tif Register%s.Fn == nil {\n", method.Name)
	w("\t\t// Operation not registered, fallback to notimplemented.Function, which will return the appropriate error.\n")
	w("\t\treturn f.Function.%s(", method.Name)
	for i, param := range method.Parameters {
		if i > 0 {
			w(", ")
		}
		if strings.HasPrefix(param.Type, "...") {
			w("%s...", param.Name)
		} else {
			w("%s", param.Name)
		}
	}
	w(")\n\t}\n")

	w("\treturn Register%s.Fn(f", method.Name)
	for _, param := range method.Parameters {
		w(", %s", param.Name)
		if strings.HasPrefix(param.Type, "...") {
			w("...")
		}
	}
	w(")\n")
	w("}\n")
	method.StubFunction = wBuf.String()
}
