/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package dot

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

type _ = bfloat16.BFloat16
type _ = float16.Float16
type _ = dtypes.Number

func init() {

	// DTypeMap: dotGeneralKernelDTypeMap
	dotGeneralKernelDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, buildDotGeneralKernel[float32])
	dotGeneralKernelDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, buildDotGeneralKernel[float64])
	dotGeneralKernelDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, buildDotGeneralKernel[int16])
	dotGeneralKernelDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, buildDotGeneralKernel[int32])
	dotGeneralKernelDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, buildDotGeneralKernel[int64])
	dotGeneralKernelDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, buildDotGeneralKernel[int8])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, buildDotGeneralKernel[uint16])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, buildDotGeneralKernel[uint32])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, buildDotGeneralKernel[uint64])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, buildDotGeneralKernel[uint8])

	// DTypeMap: dotGeneralSmallMatMulDTypeMap
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int8])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint8])

	// DTypeMap: FlatToBlockDTypeMap
	FlatToBlockDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[bfloat16.BFloat16])
	FlatToBlockDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float16.Float16])
	FlatToBlockDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float32])
	FlatToBlockDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float64])
	FlatToBlockDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int16])
	FlatToBlockDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int32])
	FlatToBlockDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int64])
	FlatToBlockDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int8])
	FlatToBlockDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint16])
	FlatToBlockDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint32])
	FlatToBlockDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint64])
	FlatToBlockDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint8])

	// DTypeMap: OutputBlockToFlatDTypeMap
	OutputBlockToFlatDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, copyOutputBlockToFlat[float32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, copyOutputBlockToFlat[float64])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, copyOutputBlockToFlat[int16])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, copyOutputBlockToFlat[int32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, copyOutputBlockToFlat[int64])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, copyOutputBlockToFlat[int8])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint16])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint64])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint8])

	// DTypeMap: SmallTransposedDTypeMap
	SmallTransposedDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execSmallTransposedGeneric[float32])
	SmallTransposedDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execSmallTransposedGeneric[float64])
	SmallTransposedDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execSmallTransposedGeneric[int16])
	SmallTransposedDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execSmallTransposedGeneric[int32])
	SmallTransposedDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execSmallTransposedGeneric[int64])
	SmallTransposedDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execSmallTransposedGeneric[int8])
	SmallTransposedDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execSmallTransposedGeneric[uint16])
	SmallTransposedDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execSmallTransposedGeneric[uint32])
	SmallTransposedDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execSmallTransposedGeneric[uint64])
	SmallTransposedDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execSmallTransposedGeneric[uint8])

	// DTypeMap: SmallTransposedDTypeMap
	SmallTransposedDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, execSmallTransposedHalfPrecision[bfloat16.BFloat16])
	SmallTransposedDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, execSmallTransposedHalfPrecision[float16.Float16])

	// DTypePairMap: callImplementationDTypePairMap (ints, same)
	callImplementationDTypePairMap.Register(dtypes.Int16, dtypes.Int16, gobackend.PriorityGeneric, callImplementationGeneric[int16, int16])
	callImplementationDTypePairMap.Register(dtypes.Int32, dtypes.Int32, gobackend.PriorityGeneric, callImplementationGeneric[int32, int32])
	callImplementationDTypePairMap.Register(dtypes.Int64, dtypes.Int64, gobackend.PriorityGeneric, callImplementationGeneric[int64, int64])
	callImplementationDTypePairMap.Register(dtypes.Int8, dtypes.Int8, gobackend.PriorityGeneric, callImplementationGeneric[int8, int8])

	// DTypePairMap: callImplementationDTypePairMap (ints, int32,int64)
	callImplementationDTypePairMap.Register(dtypes.Int16, dtypes.Int32, gobackend.PriorityGeneric, callImplementationGeneric[int16, int32])
	callImplementationDTypePairMap.Register(dtypes.Int16, dtypes.Int64, gobackend.PriorityGeneric, callImplementationGeneric[int16, int64])
	callImplementationDTypePairMap.Register(dtypes.Int32, dtypes.Int32, gobackend.PriorityGeneric, callImplementationGeneric[int32, int32])
	callImplementationDTypePairMap.Register(dtypes.Int32, dtypes.Int64, gobackend.PriorityGeneric, callImplementationGeneric[int32, int64])
	callImplementationDTypePairMap.Register(dtypes.Int64, dtypes.Int32, gobackend.PriorityGeneric, callImplementationGeneric[int64, int32])
	callImplementationDTypePairMap.Register(dtypes.Int64, dtypes.Int64, gobackend.PriorityGeneric, callImplementationGeneric[int64, int64])
	callImplementationDTypePairMap.Register(dtypes.Int8, dtypes.Int32, gobackend.PriorityGeneric, callImplementationGeneric[int8, int32])
	callImplementationDTypePairMap.Register(dtypes.Int8, dtypes.Int64, gobackend.PriorityGeneric, callImplementationGeneric[int8, int64])

	// DTypePairMap: callImplementationDTypePairMap (uints, same)
	callImplementationDTypePairMap.Register(dtypes.Uint16, dtypes.Uint16, gobackend.PriorityGeneric, callImplementationGeneric[uint16, uint16])
	callImplementationDTypePairMap.Register(dtypes.Uint32, dtypes.Uint32, gobackend.PriorityGeneric, callImplementationGeneric[uint32, uint32])
	callImplementationDTypePairMap.Register(dtypes.Uint64, dtypes.Uint64, gobackend.PriorityGeneric, callImplementationGeneric[uint64, uint64])
	callImplementationDTypePairMap.Register(dtypes.Uint8, dtypes.Uint8, gobackend.PriorityGeneric, callImplementationGeneric[uint8, uint8])

	// DTypePairMap: callImplementationDTypePairMap (uints, uint32,uint64)
	callImplementationDTypePairMap.Register(dtypes.Uint16, dtypes.Uint32, gobackend.PriorityGeneric, callImplementationGeneric[uint16, uint32])
	callImplementationDTypePairMap.Register(dtypes.Uint16, dtypes.Uint64, gobackend.PriorityGeneric, callImplementationGeneric[uint16, uint64])
	callImplementationDTypePairMap.Register(dtypes.Uint32, dtypes.Uint32, gobackend.PriorityGeneric, callImplementationGeneric[uint32, uint32])
	callImplementationDTypePairMap.Register(dtypes.Uint32, dtypes.Uint64, gobackend.PriorityGeneric, callImplementationGeneric[uint32, uint64])
	callImplementationDTypePairMap.Register(dtypes.Uint64, dtypes.Uint32, gobackend.PriorityGeneric, callImplementationGeneric[uint64, uint32])
	callImplementationDTypePairMap.Register(dtypes.Uint64, dtypes.Uint64, gobackend.PriorityGeneric, callImplementationGeneric[uint64, uint64])
	callImplementationDTypePairMap.Register(dtypes.Uint8, dtypes.Uint32, gobackend.PriorityGeneric, callImplementationGeneric[uint8, uint32])
	callImplementationDTypePairMap.Register(dtypes.Uint8, dtypes.Uint64, gobackend.PriorityGeneric, callImplementationGeneric[uint8, uint64])

	// DTypePairMap: callImplementationDTypePairMap (floats, floats)
	callImplementationDTypePairMap.Register(dtypes.Float32, dtypes.Float32, gobackend.PriorityGeneric, callImplementationGeneric[float32, float32])
	callImplementationDTypePairMap.Register(dtypes.Float32, dtypes.Float64, gobackend.PriorityGeneric, callImplementationGeneric[float32, float64])
	callImplementationDTypePairMap.Register(dtypes.Float64, dtypes.Float32, gobackend.PriorityGeneric, callImplementationGeneric[float64, float32])
	callImplementationDTypePairMap.Register(dtypes.Float64, dtypes.Float64, gobackend.PriorityGeneric, callImplementationGeneric[float64, float64])

	// DTypePairMap: callImplementationDTypePairMap (half, float32,half)
	callImplementationDTypePairMap.Register(dtypes.BFloat16, dtypes.BFloat16, gobackend.PriorityGeneric, callImplementationGeneric[bfloat16.BFloat16, bfloat16.BFloat16])
	callImplementationDTypePairMap.Register(dtypes.BFloat16, dtypes.Float16, gobackend.PriorityGeneric, callImplementationGeneric[bfloat16.BFloat16, float16.Float16])
	callImplementationDTypePairMap.Register(dtypes.BFloat16, dtypes.Float32, gobackend.PriorityGeneric, callImplementationGeneric[bfloat16.BFloat16, float32])
	callImplementationDTypePairMap.Register(dtypes.Float16, dtypes.BFloat16, gobackend.PriorityGeneric, callImplementationGeneric[float16.Float16, bfloat16.BFloat16])
	callImplementationDTypePairMap.Register(dtypes.Float16, dtypes.Float16, gobackend.PriorityGeneric, callImplementationGeneric[float16.Float16, float16.Float16])
	callImplementationDTypePairMap.Register(dtypes.Float16, dtypes.Float32, gobackend.PriorityGeneric, callImplementationGeneric[float16.Float16, float32])

}
