/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package dot

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

func init() {

	// DTypeMap: FlatToBlockDTypeMap
	FlatToBlockDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int8])
	FlatToBlockDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int16])
	FlatToBlockDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int32])
	FlatToBlockDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[int64])
	FlatToBlockDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint8])
	FlatToBlockDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint16])
	FlatToBlockDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint32])
	FlatToBlockDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[uint64])
	FlatToBlockDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float32])
	FlatToBlockDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float64])
	FlatToBlockDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[bfloat16.BFloat16])
	FlatToBlockDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, CopyFlatToBlockShapeGeneric[float16.Float16])

	// DTypeMap: NormalizeShapeDTypeMap
	NormalizeShapeDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, NormalizeShape[int8])
	NormalizeShapeDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, NormalizeShape[int16])
	NormalizeShapeDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, NormalizeShape[int32])
	NormalizeShapeDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, NormalizeShape[int64])
	NormalizeShapeDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, NormalizeShape[uint8])
	NormalizeShapeDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, NormalizeShape[uint16])
	NormalizeShapeDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, NormalizeShape[uint32])
	NormalizeShapeDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, NormalizeShape[uint64])
	NormalizeShapeDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, NormalizeShape[float32])
	NormalizeShapeDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, NormalizeShape[float64])
	NormalizeShapeDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, NormalizeShape[bfloat16.BFloat16])
	NormalizeShapeDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, NormalizeShape[float16.Float16])

	// DTypeMap: OutputBlockToFlatDTypeMap
	OutputBlockToFlatDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, copyOutputBlockToFlat[int8])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, copyOutputBlockToFlat[int16])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, copyOutputBlockToFlat[int32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, copyOutputBlockToFlat[int64])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint8])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint16])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, copyOutputBlockToFlat[uint64])
	OutputBlockToFlatDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, copyOutputBlockToFlat[float32])
	OutputBlockToFlatDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, copyOutputBlockToFlat[float64])

	// DTypeMap: dotGeneralKernelDTypeMap
	dotGeneralKernelDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, buildDotGeneralKernel[int8])
	dotGeneralKernelDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, buildDotGeneralKernel[int16])
	dotGeneralKernelDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, buildDotGeneralKernel[int32])
	dotGeneralKernelDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, buildDotGeneralKernel[int64])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, buildDotGeneralKernel[uint8])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, buildDotGeneralKernel[uint16])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, buildDotGeneralKernel[uint32])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, buildDotGeneralKernel[uint64])
	dotGeneralKernelDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, buildDotGeneralKernel[float32])
	dotGeneralKernelDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, buildDotGeneralKernel[float64])

	// DTypeMap: dotGeneralNormalizedDTypeMap
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int8])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int16])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int64])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint8])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint16])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint64])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[float32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[float64])

	// DTypeMap: dotGeneralSmallMatMulDTypeMap
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int8])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint8])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float64])

}
