// Code generated by "enumer -type ExecutionPath -output=gen_execution_path_enumer.go dot.go"; DO NOT EDIT.

package dot

import (
	"fmt"
	"strings"
)

const _ExecutionPathName = "AutoSelectPathSmallTransposedPathBlockedPathSmallMatMulPathPackgemmPathHighwayPathCheckPath"

var _ExecutionPathIndex = [...]uint8{0, 14, 33, 44, 59, 71, 82, 91}

const _ExecutionPathLowerName = "autoselectpathsmalltransposedpathblockedpathsmallmatmulpathpackgemmpathhighwaypathcheckpath"

func (i ExecutionPath) String() string {
	if i < 0 || i >= ExecutionPath(len(_ExecutionPathIndex)-1) {
		return fmt.Sprintf("ExecutionPath(%d)", i)
	}
	return _ExecutionPathName[_ExecutionPathIndex[i]:_ExecutionPathIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExecutionPathNoOp() {
	var x [1]struct{}
	_ = x[AutoSelectPath-(0)]
	_ = x[SmallTransposedPath-(1)]
	_ = x[BlockedPath-(2)]
	_ = x[SmallMatMulPath-(3)]
	_ = x[PackgemmPath-(4)]
	_ = x[HighwayPath-(5)]
	_ = x[CheckPath-(6)]
}

var _ExecutionPathValues = []ExecutionPath{AutoSelectPath, SmallTransposedPath, BlockedPath, SmallMatMulPath, PackgemmPath, HighwayPath, CheckPath}

var _ExecutionPathNameToValueMap = map[string]ExecutionPath{
	_ExecutionPathName[0:14]:       AutoSelectPath,
	_ExecutionPathLowerName[0:14]:  AutoSelectPath,
	_ExecutionPathName[14:33]:      SmallTransposedPath,
	_ExecutionPathLowerName[14:33]: SmallTransposedPath,
	_ExecutionPathName[33:44]:      BlockedPath,
	_ExecutionPathLowerName[33:44]: BlockedPath,
	_ExecutionPathName[44:59]:      SmallMatMulPath,
	_ExecutionPathLowerName[44:59]: SmallMatMulPath,
	_ExecutionPathName[59:71]:      PackgemmPath,
	_ExecutionPathLowerName[59:71]: PackgemmPath,
	_ExecutionPathName[71:82]:      HighwayPath,
	_ExecutionPathLowerName[71:82]: HighwayPath,
	_ExecutionPathName[82:91]:      CheckPath,
	_ExecutionPathLowerName[82:91]: CheckPath,
}

var _ExecutionPathNames = []string{
	_ExecutionPathName[0:14],
	_ExecutionPathName[14:33],
	_ExecutionPathName[33:44],
	_ExecutionPathName[44:59],
	_ExecutionPathName[59:71],
	_ExecutionPathName[71:82],
	_ExecutionPathName[82:91],
}

// ExecutionPathString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExecutionPathString(s string) (ExecutionPath, error) {
	if val, ok := _ExecutionPathNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExecutionPathNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExecutionPath values", s)
}

// ExecutionPathValues returns all values of the enum
func ExecutionPathValues() []ExecutionPath {
	return _ExecutionPathValues
}

// ExecutionPathStrings returns a slice of all String values of the enum
func ExecutionPathStrings() []string {
	strs := make([]string, len(_ExecutionPathNames))
	copy(strs, _ExecutionPathNames)
	return strs
}

// IsAExecutionPath returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExecutionPath) IsAExecutionPath() bool {
	for _, v := range _ExecutionPathValues {
		if i == v {
			return true
		}
	}
	return false
}
