// Code generated by "enumer -type ExecutionPath -output=gen_execution_path_enumer.go dot.go"; DO NOT EDIT.

package dot

import (
	"fmt"
	"strings"
)

const _ExecutionPathName = "AutoSelectPathNormalizedPathBlockedPathSmallMatMulPathPackgemmPathHighwayPathCheckPath"

var _ExecutionPathIndex = [...]uint8{0, 14, 28, 39, 54, 66, 77, 86}

const _ExecutionPathLowerName = "autoselectpathnormalizedpathblockedpathsmallmatmulpathpackgemmpathhighwaypathcheckpath"

func (i ExecutionPath) String() string {
	if i < 0 || i >= ExecutionPath(len(_ExecutionPathIndex)-1) {
		return fmt.Sprintf("ExecutionPath(%d)", i)
	}
	return _ExecutionPathName[_ExecutionPathIndex[i]:_ExecutionPathIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExecutionPathNoOp() {
	var x [1]struct{}
	_ = x[AutoSelectPath-(0)]
	_ = x[NormalizedPath-(1)]
	_ = x[BlockedPath-(2)]
	_ = x[SmallMatMulPath-(3)]
	_ = x[PackgemmPath-(4)]
	_ = x[HighwayPath-(5)]
	_ = x[CheckPath-(6)]
}

var _ExecutionPathValues = []ExecutionPath{AutoSelectPath, NormalizedPath, BlockedPath, SmallMatMulPath, PackgemmPath, HighwayPath, CheckPath}

var _ExecutionPathNameToValueMap = map[string]ExecutionPath{
	_ExecutionPathName[0:14]:       AutoSelectPath,
	_ExecutionPathLowerName[0:14]:  AutoSelectPath,
	_ExecutionPathName[14:28]:      NormalizedPath,
	_ExecutionPathLowerName[14:28]: NormalizedPath,
	_ExecutionPathName[28:39]:      BlockedPath,
	_ExecutionPathLowerName[28:39]: BlockedPath,
	_ExecutionPathName[39:54]:      SmallMatMulPath,
	_ExecutionPathLowerName[39:54]: SmallMatMulPath,
	_ExecutionPathName[54:66]:      PackgemmPath,
	_ExecutionPathLowerName[54:66]: PackgemmPath,
	_ExecutionPathName[66:77]:      HighwayPath,
	_ExecutionPathLowerName[66:77]: HighwayPath,
	_ExecutionPathName[77:86]:      CheckPath,
	_ExecutionPathLowerName[77:86]: CheckPath,
}

var _ExecutionPathNames = []string{
	_ExecutionPathName[0:14],
	_ExecutionPathName[14:28],
	_ExecutionPathName[28:39],
	_ExecutionPathName[39:54],
	_ExecutionPathName[54:66],
	_ExecutionPathName[66:77],
	_ExecutionPathName[77:86],
}

// ExecutionPathString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExecutionPathString(s string) (ExecutionPath, error) {
	if val, ok := _ExecutionPathNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExecutionPathNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExecutionPath values", s)
}

// ExecutionPathValues returns all values of the enum
func ExecutionPathValues() []ExecutionPath {
	return _ExecutionPathValues
}

// ExecutionPathStrings returns a slice of all String values of the enum
func ExecutionPathStrings() []string {
	strs := make([]string, len(_ExecutionPathNames))
	copy(strs, _ExecutionPathNames)
	return strs
}

// IsAExecutionPath returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExecutionPath) IsAExecutionPath() bool {
	for _, v := range _ExecutionPathValues {
		if i == v {
			return true
		}
	}
	return false
}
