/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package dot

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

func init() {

	// DTypeMap: dotGeneralSmallMatMulDTypeMap
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int8])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[int64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint8])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint16])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[uint64])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float32])
	dotGeneralSmallMatMulDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execDotGeneralSmallMatMulGeneric[float64])

	// DTypeMap: dotGeneralFlatToBlockDTypeMap
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[int8])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[int16])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[int32])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[int64])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[uint8])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[uint16])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[uint32])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[uint64])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[float32])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[float64])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[bfloat16.BFloat16])
	dotGeneralFlatToBlockDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, dgCopyFlatToBlockShape[float16.Float16])

	// DTypeMap: dotGeneralOutputBlockToFlatDTypeMap
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[int8])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[int16])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[int32])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[int64])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[uint8])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[uint16])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[uint32])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[uint64])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[float32])
	dotGeneralOutputBlockToFlatDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, dgCopyOutputBlockToFlat[float64])

	// DTypeMap: dotGeneralKernelDTypeMap
	dotGeneralKernelDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, buildDotGeneralKernel[int8])
	dotGeneralKernelDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, buildDotGeneralKernel[int16])
	dotGeneralKernelDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, buildDotGeneralKernel[int32])
	dotGeneralKernelDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, buildDotGeneralKernel[int64])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, buildDotGeneralKernel[uint8])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, buildDotGeneralKernel[uint16])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, buildDotGeneralKernel[uint32])
	dotGeneralKernelDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, buildDotGeneralKernel[uint64])
	dotGeneralKernelDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, buildDotGeneralKernel[float32])
	dotGeneralKernelDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, buildDotGeneralKernel[float64])

	// DTypeMap: dotGeneralNormalizeShapeDTypeMap
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, dgNormalizeShape[int8])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, dgNormalizeShape[int16])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, dgNormalizeShape[int32])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, dgNormalizeShape[int64])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, dgNormalizeShape[uint8])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, dgNormalizeShape[uint16])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, dgNormalizeShape[uint32])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, dgNormalizeShape[uint64])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, dgNormalizeShape[float32])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, dgNormalizeShape[float64])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, dgNormalizeShape[bfloat16.BFloat16])
	dotGeneralNormalizeShapeDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, dgNormalizeShape[float16.Float16])

	// DTypeMap: dotGeneralNormalizedDTypeMap
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int8])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int16])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[int64])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint8])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint16])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[uint64])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[float32])
	dotGeneralNormalizedDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execNormalizedDotGeneralGeneric[float64])

}
