// *** DO NOT EDIT ***: File generated by internal/cmd/alternates_generator.
// - Base source file (edit this one): small_matmul_alt_base.go
// - Tag used for this generation: f16

// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package dot

import (
	//alt:bf16  "github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16" //alt:f16
	"github.com/gomlx/compute/internal/gobackend"
)

// execDotGeneralSmallMatMul* executes matrix multiplication without transpose.
//
// Memory layout for row-major tensors [M, K] × [K, N] → [M, N]:
//
//	LHS [M, K]: element [m, k] at index m*K + k
//	  → Row m is CONTIGUOUS: [m*K, m*K+1, ..., m*K+K-1] - Good cache locality
//
//	RHS [K, N]: element [k, n] at index k*N + n
//	  → Column n is STRIDED: [n, N+n, 2N+n, ...] with stride N - Poor cache locality
//
//	Output [M, N]: element [m, n] at index m*N + n
//
// The strided RHS access is the key limitation of this path. For large K or N,
// each RHS element access may cause a cache miss. This is why we limit this path
// to small matrices (see smallMatMulMaxContractingSize).
//
// For large matrices, execDotGeneralSmallNormalized transposes RHS to [N, K] form where
// "row" n (the original column) becomes contiguous, enabling efficient vectorization.
//
// BFloat16/Float16 variants accumulate in float32 for numerical stability, then
// convert to the native dtype when writing to output (fused conversion).
//
//alt:base func execDotGeneralSmallMatMulGeneric[T gobackend.PODNumericConstraints](
//alt:bf16  func execDotGeneralSmallMatMulBFloat16(
func execDotGeneralSmallMatMulFloat16( //alt:f16
	_ *gobackend.Backend, lhs, rhs *gobackend.Buffer, params *NodeData, output *gobackend.Buffer) {

	//alt:base lhsFlat := lhs.Flat.([]T)
	//alt:base rhsFlat := rhs.Flat.([]T)
	//alt:base outputFlat := output.Flat.([]T)
	//alt:bf16  lhsFlat := lhs.Flat.([]bfloat16.BFloat16)
	//alt:bf16  rhsFlat := rhs.Flat.([]bfloat16.BFloat16)
	//alt:bf16  outputFlat := output.Flat.([]bfloat16.BFloat16)
	lhsFlat := lhs.Flat.([]float16.Float16)       //alt:f16
	rhsFlat := rhs.Flat.([]float16.Float16)       //alt:f16
	outputFlat := output.Flat.([]float16.Float16) //alt:f16

	batchSize := params.BatchSize
	lhsCrossSize := params.LHSCrossSize       // M
	rhsCrossSize := params.RHSCrossSize       // N
	contractingSize := params.ContractingSize // K

	lhsBatchStride := lhsCrossSize * contractingSize // M * K elements per batch
	rhsBatchStride := contractingSize * rhsCrossSize // K * N elements per batch (for [B,K,N] layout)
	outputBatchStride := lhsCrossSize * rhsCrossSize // M * N elements per batch

	// For row-major RHS [K, N], the stride between elements in the same column is N
	rhsColStride := rhsCrossSize // N

	for batchIdx := range batchSize {
		lhsBaseIdx := batchIdx * lhsBatchStride
		rhsBaseIdx := batchIdx * rhsBatchStride
		outputBaseIdx := batchIdx * outputBatchStride

		for m := range lhsCrossSize {
			lhsRowStart := lhsBaseIdx + m*contractingSize
			outputRowStart := outputBaseIdx + m*rhsCrossSize

			for n := range rhsCrossSize {
				// For column n in row-major [K,N], element [k,n] is at k*N + n
				rhsColStart := rhsBaseIdx + n
				//alt:base var sum T
				var sum float32 //alt:bf16|f16

				// Scalar loop with strided RHS access
				// We cannot use NEON here because RHS column elements are not contiguous
				k := 0
				for ; k+3 < contractingSize; k += 4 {
					/* //alt:base{
					sum += lhsFlat[lhsRowStart+k]*rhsFlat[rhsColStart+k*rhsColStride] +
						lhsFlat[lhsRowStart+k+1]*rhsFlat[rhsColStart+(k+1)*rhsColStride] +
						lhsFlat[lhsRowStart+k+2]*rhsFlat[rhsColStart+(k+2)*rhsColStride] +
						lhsFlat[lhsRowStart+k+3]*rhsFlat[rhsColStart+(k+3)*rhsColStride]
					*/ //alt:base}
					//alt:bf16|f16{
					sum += lhsFlat[lhsRowStart+k].Float32()*rhsFlat[rhsColStart+k*rhsColStride].Float32() +
						lhsFlat[lhsRowStart+k+1].Float32()*rhsFlat[rhsColStart+(k+1)*rhsColStride].Float32() +
						lhsFlat[lhsRowStart+k+2].Float32()*rhsFlat[rhsColStart+(k+2)*rhsColStride].Float32() +
						lhsFlat[lhsRowStart+k+3].Float32()*rhsFlat[rhsColStart+(k+3)*rhsColStride].Float32()
					//alt:bf16|f16}
				}
				for ; k < contractingSize; k++ {
					//alt:base sum += lhsFlat[lhsRowStart+k] * rhsFlat[rhsColStart+k*rhsColStride]
					sum += lhsFlat[lhsRowStart+k].Float32() * rhsFlat[rhsColStart+k*rhsColStride].Float32() //alt:bf16|f16
				}

				//alt:base outputFlat[outputRowStart+n] = sum
				//alt:bf16  outputFlat[outputRowStart+n] = bfloat16.FromFloat32(sum)
				outputFlat[outputRowStart+n] = float16.FromFloat32(sum) //alt:f16
			}
		}
	}
}
