// *** DO NOT EDIT ***: File generated by internal/cmd/alternates_generator.
// - Base source file (edit this one): nosimd_router.go
// - Tag used for this generation: half

package simd

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/internal/gobackend"
	"k8s.io/klog/v2"
)

// noSIMDRouter implements a non-SIMD matrix multiplication for the non-transposed layout.
//
// It is used when no SIMD-optimized implementation is available, or for non-supported
// dtype configuration.
//
//alt:generic func noSIMDRouter[I, O dtypes.NumberNotComplex](
func noSIMDHalfPrecisionRouter[I dtypes.HalfPrecision[I], O dtypes.NumberNotComplex]( //alt:half
	backend *gobackend.Backend,
	lhs, rhs []I,
	batchSize, lhsCrossSize, rhsCrossSize, contractingSize int,
	output []O) {

	// Check if small matrix multiplication kernel can be used.
	flopsPerMatrix := lhsCrossSize * rhsCrossSize * contractingSize
	flops := batchSize * flopsPerMatrix
	_ = flops
	if !ForceLargeVariant && (ForceSmallVariant || flops < noSIMDSmallMatMulSizeThreshold) {
		klog.V(1).Infof("Using small variant for NonTransposed non-SIMD dot-product kernel")
		matricesPerWorker := (noSIMDMinMatMulFlopsPerWorker + (flopsPerMatrix - 1)) / flopsPerMatrix
		matricesPerWorker = min(matricesPerWorker, batchSize)
		maxWorkers := 1
		if backend.Workers != nil {
			maxWorkers = backend.Workers.AdjustedMaxParallelism()
		}
		if maxWorkers == 1 || matricesPerWorker > batchSize/2 {
			// Only 1 worker, or the overhead of distributing the processing is not worth it.
			// Run the DotGeneral in one go (without parallelism).
			//alt:generic smallNoSIMDGeneric(
			smallNoSIMDHalfPrecision( //alt:half
				lhs, rhs,
				0, batchSize, lhsCrossSize, rhsCrossSize, contractingSize,
				output)
		} else {
			//alt:generic smallNoSIMDGenericParallel(
			smallNoSIMDHalfPrecisionParallel( //alt:half
				backend,
				lhs, rhs,
				batchSize, lhsCrossSize, rhsCrossSize, contractingSize,
				output, matricesPerWorker)
		}

	} else {
		klog.V(1).Infof("Using large variant for NonTransposed non-SIMD dot-product kernel")
		//alt:generic largeNoSIMDGeneric(
		largeNoSIMDHalfPrecision( //alt:half
			backend,
			lhs, rhs,
			batchSize, lhsCrossSize, rhsCrossSize, contractingSize,
			output)
	}
}
