// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package ops

import (
	//alt:half|full_half "github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/internal/gobackend" //alt:base|full
)

// This file serves the "base" version of the `execConv*` functions, as well as a template.
//
// The other versions are generated by `internal/cmd/alternates_generator`, where each line is generated
// according to a pre-set selection of tags. Lines marked with "//alt:tag1|tag2" are included or excluded
// according to the tags.
// The "//alt:base" tag indicates it's included in this base version, but will be removed in others.

// execConv* family of functions are used for ConvGeneral operations.
//
// The functions are generated by `internal/cmd/alternates_generator` based on the tags.
//
// The functions are generated for the following tags:
//
// execConvNoDilationGeneric: `base` tag; generics for native Go numeric types, no dilation or grouping handling, but faster.
// execConvNoDialtionHalf: `half` tag; supports BFloat16 and Float16, fast but no dilation or grouping handling.
// execConvGeneric: `full`; support dilation and grouping, with a latency penalty.
// execConvHalf: supports BFloat16 and Float16, fast but no dilation or grouping handling.
func execConvNoDilationGeneric[T gobackend.PODNumericConstraints](plan convGeneralExecPlan) error { //alt:base
	//alt:half func execConvNoDilationHalf[T dtypes.HalfPrecision[T], P dtypes.HalfPrecisionPtr[T]](plan convGeneralExecPlan) error {
	//alt:full func execConvGeneric[T gobackend.PODNumericConstraints](plan convGeneralExecPlan) error {
	//alt:full_half func execConvHalf[T dtypes.HalfPrecision[T], P dtypes.HalfPrecisionPtr[T]](plan convGeneralExecPlan) error {

	// Shortcuts (and maybe move these values to the stack for faster access)
	inputFlat := plan.inputFlat.([]T)   //alt:base|full
	kernelFlat := plan.kernelFlat.([]T) //alt:base|full
	outputFlat := plan.outputFlat.([]T) //alt:base|full
	//alt:half|full_half inputFlat := plan.inputFlat.([]T)
	//alt:half|full_half kernelFlat := plan.kernelFlat.([]T)
	//alt:half|full_half outputFlat := plan.outputFlat.([]T)
	inputShape := plan.inputShape
	kernelShape := plan.kernelShape
	outputShape := plan.outputShape
	rank := outputShape.Rank() // same rank for input and kernel.
	//spatialRank := rank - 2
	params := plan.params
	axes := params.axes
	paddings := params.paddings
	convStrides := params.strides

	inputBatchAxis := axes.InputBatch
	inputChannelsAxis := axes.InputChannels
	inputSpatialDims := params.dilatedInputSpatialDims
	inputSpatialStrides := params.inputSpatialStrides
	//alt:full|full_half inputDilations := params.inputDilations
	//alt:full|full_half kernelDilations := params.kernelDilations
	//alt:full|full_half batchGroupCount := params.batchGroupCount
	//alt:full|full_half outputBatchSize := outputShape.Dimensions[inputBatchAxis]
	//alt:full|full_half channelGroupCount := params.channelGroupCount
	//alt:full|full_half numOutputChannelsPerGroup := outputShape.Dimensions[axes.OutputChannels] / channelGroupCount
	//alt:full|full_half numOutputChannelsPerBatchGroup := outputShape.Dimensions[axes.OutputChannels] / batchGroupCount

	outputBatchAxis := axes.OutputBatch
	outputChannelsAxis := axes.OutputChannels
	outputSpatialAxes := axes.OutputSpatial
	kernelInputChannelsAxis := axes.KernelInputChannels
	kernelOutputChannelsAxis := axes.KernelOutputChannels
	kernelSpatialAxes := axes.KernelSpatial
	kernelNumInputChannels := kernelShape.Dimensions[kernelInputChannelsAxis]

	// Indices we'll be iterating over.
	var outputFlatIdx int

	// Indices and strides: note we don't use an inputIndices because we only keep an inputFlatIndex.
	outputIndices := make([]int, rank)
	kernelIndices := make([]int, rank)

	inputStrides := inputShape.Strides()
	kernelStrides := kernelShape.Strides()

	// Loop sequentially over all output positions:
	for outputFlatIdx, outputIndices = range outputShape.IterOn(outputIndices) {
		batchIdx := outputIndices[outputBatchAxis]
		outputChannel := outputIndices[outputChannelsAxis]
		//alt:full|full_half if batchGroupCount > 1 {
		//alt:full|full_half subBatchIdx := outputChannel / numOutputChannelsPerBatchGroup
		//alt:full|full_half batchIdx = subBatchIdx*outputBatchSize + batchIdx
		//alt:full|full_half }
		baseInputFlatIdx := batchIdx * inputStrides[inputBatchAxis]

		// Loop over the kernel spatial axes, with the outputChannel given by the output loop.
		kernelIndices[kernelOutputChannelsAxis] = outputChannel
		var outputValue T //alt:base|full
		//alt:half|full_half var outputValue float32
		var kernelFlatIdx int
	kernelLoop:
		for kernelFlatIdx, kernelIndices = range kernelShape.IterOnAxes(kernelSpatialAxes, kernelStrides, kernelIndices) {
			// Calculate the corresponding position in the input.
			inputFlatIdx := baseInputFlatIdx
			for spatialIdx, kernelSpatialAxis := range axes.KernelSpatial {
				kernelIdx := kernelIndices[kernelSpatialAxis]
				//alt:full|full_half kernelDilation := kernelDilations[spatialIdx]
				//alt:full|full_half kernelIdx *= kernelDilation
				outputSpatialAxis := outputSpatialAxes[spatialIdx]
				outputIdx := outputIndices[outputSpatialAxis]
				inputIdx := outputIdx*convStrides[spatialIdx] + kernelIdx - paddings[spatialIdx][0]
				//alt:full|full_half inputDilation := inputDilations[spatialIdx]
				if inputIdx < 0 || inputIdx >= inputSpatialDims[spatialIdx] { //alt:base|half
					//alt:full|full_half if inputIdx < 0 || inputIdx >= inputSpatialDims[spatialIdx] || (inputDilation > 1 && inputIdx%inputDilation != 0) {
					// Index is in the padded area, we can move to the next kernel position.
					continue kernelLoop
				}
				//alt:full|full_half inputIdx /= inputDilation // Make the dilated index back to the original input.
				inputFlatIdx += inputIdx * inputSpatialStrides[spatialIdx]
			}

			// Accumulate over all the kernel/input channels.
			inputChannelStride := inputStrides[inputChannelsAxis]
			kernelChannelStride := kernelStrides[kernelInputChannelsAxis]
			//alt:full|full_half if channelGroupCount > 1 {
			//alt:full|full_half featureGroup := outputChannel / numOutputChannelsPerGroup
			//alt:full|full_half inputFlatIdx += inputChannelStride * (featureGroup*kernelNumInputChannels)
			//alt:full|full_half }
			for range kernelNumInputChannels {
				inputValue := inputFlat[inputFlatIdx]
				kernelValue := kernelFlat[kernelFlatIdx]
				outputValue += inputValue * kernelValue //alt:base|full
				//alt:half|full_half outputValue += inputValue.Float32() * kernelValue.Float32()
				inputFlatIdx += inputChannelStride
				kernelFlatIdx += kernelChannelStride
			}
		}

		// Update output with accumulated value from the convolution of the kernel at this position.
		outputFlat[outputFlatIdx] = outputValue //alt:base|full
		//alt:half|full_half P(&outputFlat[outputFlatIdx]).SetFloat32(outputValue)
	}
	return nil
}
