/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package ops

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

func init() {

	// DTypeMap: broadcastInDimDTypeMap
	broadcastInDimDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int8])
	broadcastInDimDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int16])
	broadcastInDimDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int32])
	broadcastInDimDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int64])
	broadcastInDimDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint8])
	broadcastInDimDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint16])
	broadcastInDimDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint32])
	broadcastInDimDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint64])
	broadcastInDimDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float32])
	broadcastInDimDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float64])
	broadcastInDimDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[bfloat16.BFloat16])
	broadcastInDimDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float16.Float16])
	broadcastInDimDTypeMap.Register(dtypes.Bool, gobackend.PriorityGeneric, execBroadcastInDimGeneric[bool])

	// DTypeMap: gatherDTypeMap
	gatherDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execGatherGeneric[int8])
	gatherDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execGatherGeneric[int16])
	gatherDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execGatherGeneric[int32])
	gatherDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execGatherGeneric[int64])
	gatherDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execGatherGeneric[uint8])
	gatherDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execGatherGeneric[uint16])
	gatherDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execGatherGeneric[uint32])
	gatherDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execGatherGeneric[uint64])

	// DTypeMap: iotaDTypeMap
	iotaDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execIotaGeneric[int8])
	iotaDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execIotaGeneric[int16])
	iotaDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execIotaGeneric[int32])
	iotaDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execIotaGeneric[int64])
	iotaDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execIotaGeneric[uint8])
	iotaDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execIotaGeneric[uint16])
	iotaDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execIotaGeneric[uint32])
	iotaDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execIotaGeneric[uint64])
	iotaDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execIotaGeneric[float32])
	iotaDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execIotaGeneric[float64])

}
