// *** DO NOT EDIT ***: File generated by internal/cmd/alternates_generator.
// - Base source file (edit this one): convgeneral_exec_base.go
// - Tag used for this generation: full_half

// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package ops

import (
	"github.com/gomlx/compute/dtypes" //alt:half|full_half
	//alt:base|full "github.com/gomlx/compute/internal/gobackend"
)

// This file serves the "base" version of the `execConv*` functions, as well as a template.
//
// The other versions are generated by `internal/cmd/alternates_generator`, where each line is generated
//alt:tag1|tag2"  // according to a pre-set selection of tags. Lines marked with " are included or excluded
// according to the tags.
//alt:base"  // The " tag indicates it's included in this base version, but will be removed in others.

// execConv* family of functions are used for ConvGeneral operations.
//
// The functions are generated by `internal/cmd/alternates_generator` based on the tags.
//
// The functions are generated for the following tags:
//
// execConvNoDilationGeneric: `base` tag; generics for native Go numeric types, no dilation or grouping handling, but faster.
// execConvNoDialtionHalf: `half` tag; supports BFloat16 and Float16, fast but no dilation or grouping handling.
// execConvGeneric: `full`; support dilation and grouping, with a latency penalty.
// execConvHalf: supports BFloat16 and Float16, fast but no dilation or grouping handling.
//
//alt:base func execConvNoDilationGeneric[T gobackend.PODNumericConstraints](plan convGeneralExecPlan) error {
//alt:half  func execConvNoDilationHalf[T dtypes.HalfPrecision[T], P dtypes.HalfPrecisionPtr[T]](plan convGeneralExecPlan) error {
//alt:full  func execConvGeneric[T gobackend.PODNumericConstraints](plan convGeneralExecPlan) error {
func execConvHalf[T dtypes.HalfPrecision[T], P dtypes.HalfPrecisionPtr[T]](plan convGeneralExecPlan) error { //alt:full_half

	// Shortcuts (and maybe move these values to the stack for faster access)
	//alt:base|full inputFlat := plan.inputFlat.([]T)
	//alt:base|full kernelFlat := plan.kernelFlat.([]T)
	//alt:base|full outputFlat := plan.outputFlat.([]T)
	inputFlat := plan.inputFlat.([]T)   //alt:half|full_half
	kernelFlat := plan.kernelFlat.([]T) //alt:half|full_half
	outputFlat := plan.outputFlat.([]T) //alt:half|full_half
	inputShape := plan.inputShape
	kernelShape := plan.kernelShape
	outputShape := plan.outputShape
	rank := outputShape.Rank() // same rank for input and kernel.
	//spatialRank := rank - 2
	params := plan.params
	axes := params.axes
	paddings := params.paddings
	convStrides := params.strides

	inputBatchAxis := axes.InputBatch
	inputChannelsAxis := axes.InputChannels
	inputSpatialDims := params.dilatedInputSpatialDims
	inputSpatialStrides := params.inputSpatialStrides
	inputDilations := params.inputDilations                                                         //alt:full|full_half
	kernelDilations := params.kernelDilations                                                       //alt:full|full_half
	batchGroupCount := params.batchGroupCount                                                       //alt:full|full_half
	outputBatchSize := outputShape.Dimensions[inputBatchAxis]                                       //alt:full|full_half
	channelGroupCount := params.channelGroupCount                                                   //alt:full|full_half
	numOutputChannelsPerGroup := outputShape.Dimensions[axes.OutputChannels] / channelGroupCount    //alt:full|full_half
	numOutputChannelsPerBatchGroup := outputShape.Dimensions[axes.OutputChannels] / batchGroupCount //alt:full|full_half

	outputBatchAxis := axes.OutputBatch
	outputChannelsAxis := axes.OutputChannels
	outputSpatialAxes := axes.OutputSpatial
	kernelInputChannelsAxis := axes.KernelInputChannels
	kernelOutputChannelsAxis := axes.KernelOutputChannels
	kernelSpatialAxes := axes.KernelSpatial
	kernelNumInputChannels := kernelShape.Dimensions[kernelInputChannelsAxis]

	// Indices we'll be iterating over.
	var outputFlatIdx int

	// Indices and strides: note we don't use an inputIndices because we only keep an inputFlatIndex.
	outputIndices := make([]int, rank)
	kernelIndices := make([]int, rank)

	inputStrides := inputShape.Strides()
	kernelStrides := kernelShape.Strides()

	// Loop sequentially over all output positions:
	for outputFlatIdx, outputIndices = range outputShape.IterOn(outputIndices) {
		batchIdx := outputIndices[outputBatchAxis]
		outputChannel := outputIndices[outputChannelsAxis]
		if batchGroupCount > 1 { //alt:full|full_half
			subBatchIdx := outputChannel / numOutputChannelsPerBatchGroup //alt:full|full_half
			batchIdx = subBatchIdx*outputBatchSize + batchIdx             //alt:full|full_half
		} //alt:full|full_half
		baseInputFlatIdx := batchIdx * inputStrides[inputBatchAxis]

		// Loop over the kernel spatial axes, with the outputChannel given by the output loop.
		kernelIndices[kernelOutputChannelsAxis] = outputChannel
		//alt:base|full var outputValue T
		var outputValue float32 //alt:half|full_half
		var kernelFlatIdx int
	kernelLoop:
		for kernelFlatIdx, kernelIndices = range kernelShape.IterOnAxes(kernelSpatialAxes, kernelStrides, kernelIndices) {
			// Calculate the corresponding position in the input.
			inputFlatIdx := baseInputFlatIdx
			for spatialIdx, kernelSpatialAxis := range axes.KernelSpatial {
				kernelIdx := kernelIndices[kernelSpatialAxis]
				kernelDilation := kernelDilations[spatialIdx] //alt:full|full_half
				kernelIdx *= kernelDilation                   //alt:full|full_half
				outputSpatialAxis := outputSpatialAxes[spatialIdx]
				outputIdx := outputIndices[outputSpatialAxis]
				inputIdx := outputIdx*convStrides[spatialIdx] + kernelIdx - paddings[spatialIdx][0]
				inputDilation := inputDilations[spatialIdx] //alt:full|full_half
				//alt:base|half if inputIdx < 0 || inputIdx >= inputSpatialDims[spatialIdx] {
				if inputIdx < 0 || inputIdx >= inputSpatialDims[spatialIdx] || (inputDilation > 1 && inputIdx%inputDilation != 0) { //alt:full|full_half
					// Index is in the padded area, we can move to the next kernel position.
					continue kernelLoop
				}
				inputIdx /= inputDilation // Make the dilated index back to the original input. //alt:full|full_half
				inputFlatIdx += inputIdx * inputSpatialStrides[spatialIdx]
			}

			// Accumulate over all the kernel/input channels.
			inputChannelStride := inputStrides[inputChannelsAxis]
			kernelChannelStride := kernelStrides[kernelInputChannelsAxis]
			if channelGroupCount > 1 { //alt:full|full_half
				featureGroup := outputChannel / numOutputChannelsPerGroup                    //alt:full|full_half
				inputFlatIdx += inputChannelStride * (featureGroup * kernelNumInputChannels) //alt:full|full_half
			} //alt:full|full_half
			for range kernelNumInputChannels {
				inputValue := inputFlat[inputFlatIdx]
				kernelValue := kernelFlat[kernelFlatIdx]
				//alt:base|full outputValue += inputValue * kernelValue
				outputValue += inputValue.Float32() * kernelValue.Float32() //alt:half|full_half
				inputFlatIdx += inputChannelStride
				kernelFlatIdx += kernelChannelStride
			}
		}

		// Update output with accumulated value from the convolution of the kernel at this position.
		//alt:base|full outputFlat[outputFlatIdx] = outputValue
		P(&outputFlat[outputFlatIdx]).SetFloat32(outputValue) //alt:half|full_half
	}
	return nil
}
