/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package ops

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

func init() {

	// DTypeMap: applyPermutationDTypeMap
	applyPermutationDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, applyPermutationGeneric[int8])
	applyPermutationDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, applyPermutationGeneric[int16])
	applyPermutationDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, applyPermutationGeneric[int32])
	applyPermutationDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, applyPermutationGeneric[int64])
	applyPermutationDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, applyPermutationGeneric[uint8])
	applyPermutationDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, applyPermutationGeneric[uint16])
	applyPermutationDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, applyPermutationGeneric[uint32])
	applyPermutationDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, applyPermutationGeneric[uint64])
	applyPermutationDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, applyPermutationGeneric[float32])
	applyPermutationDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, applyPermutationGeneric[float64])
	applyPermutationDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, applyPermutationGeneric[bfloat16.BFloat16])
	applyPermutationDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, applyPermutationGeneric[float16.Float16])
	applyPermutationDTypeMap.Register(dtypes.Bool, gobackend.PriorityGeneric, applyPermutationGeneric[bool])

	// DTypeMap: broadcastInDimDTypeMap
	broadcastInDimDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int8])
	broadcastInDimDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int16])
	broadcastInDimDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int32])
	broadcastInDimDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[int64])
	broadcastInDimDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint8])
	broadcastInDimDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint16])
	broadcastInDimDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint32])
	broadcastInDimDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[uint64])
	broadcastInDimDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float32])
	broadcastInDimDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float64])
	broadcastInDimDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[bfloat16.BFloat16])
	broadcastInDimDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, execBroadcastInDimGeneric[float16.Float16])
	broadcastInDimDTypeMap.Register(dtypes.Bool, gobackend.PriorityGeneric, execBroadcastInDimGeneric[bool])

	// DTypeMap: gatherDTypeMap
	gatherDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execGatherGeneric[int8])
	gatherDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execGatherGeneric[int16])
	gatherDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execGatherGeneric[int32])
	gatherDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execGatherGeneric[int64])
	gatherDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execGatherGeneric[uint8])
	gatherDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execGatherGeneric[uint16])
	gatherDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execGatherGeneric[uint32])
	gatherDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execGatherGeneric[uint64])

	// DTypeMap: iotaDTypeMap
	iotaDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execIotaGeneric[int8])
	iotaDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execIotaGeneric[int16])
	iotaDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execIotaGeneric[int32])
	iotaDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execIotaGeneric[int64])
	iotaDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execIotaGeneric[uint8])
	iotaDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execIotaGeneric[uint16])
	iotaDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execIotaGeneric[uint32])
	iotaDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execIotaGeneric[uint64])
	iotaDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execIotaGeneric[float32])
	iotaDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execIotaGeneric[float64])

	// DTypeMap: reduceBitwiseAndDTypeMap
	reduceBitwiseAndDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[int8])
	reduceBitwiseAndDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[int16])
	reduceBitwiseAndDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[int32])
	reduceBitwiseAndDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[int64])
	reduceBitwiseAndDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[uint8])
	reduceBitwiseAndDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[uint16])
	reduceBitwiseAndDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[uint32])
	reduceBitwiseAndDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceBitwiseAndGeneric[uint64])

	// DTypeMap: reduceBitwiseOrDTypeMap
	reduceBitwiseOrDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[int8])
	reduceBitwiseOrDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[int16])
	reduceBitwiseOrDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[int32])
	reduceBitwiseOrDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[int64])
	reduceBitwiseOrDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[uint8])
	reduceBitwiseOrDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[uint16])
	reduceBitwiseOrDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[uint32])
	reduceBitwiseOrDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceBitwiseOrGeneric[uint64])

	// DTypeMap: reduceBitwiseXorDTypeMap
	reduceBitwiseXorDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[int8])
	reduceBitwiseXorDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[int16])
	reduceBitwiseXorDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[int32])
	reduceBitwiseXorDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[int64])
	reduceBitwiseXorDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[uint8])
	reduceBitwiseXorDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[uint16])
	reduceBitwiseXorDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[uint32])
	reduceBitwiseXorDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceBitwiseXorGeneric[uint64])

	// DTypeMap: reduceMaxDTypeMap
	reduceMaxDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceMaxGeneric[int8])
	reduceMaxDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceMaxGeneric[int16])
	reduceMaxDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceMaxGeneric[int32])
	reduceMaxDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceMaxGeneric[int64])
	reduceMaxDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceMaxGeneric[uint8])
	reduceMaxDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceMaxGeneric[uint16])
	reduceMaxDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceMaxGeneric[uint32])
	reduceMaxDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceMaxGeneric[uint64])
	reduceMaxDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execReduceMaxGeneric[float32])
	reduceMaxDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execReduceMaxGeneric[float64])

	// DTypeMap: reduceMinDTypeMap
	reduceMinDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceMinGeneric[int8])
	reduceMinDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceMinGeneric[int16])
	reduceMinDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceMinGeneric[int32])
	reduceMinDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceMinGeneric[int64])
	reduceMinDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceMinGeneric[uint8])
	reduceMinDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceMinGeneric[uint16])
	reduceMinDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceMinGeneric[uint32])
	reduceMinDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceMinGeneric[uint64])
	reduceMinDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execReduceMinGeneric[float32])
	reduceMinDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execReduceMinGeneric[float64])

	// DTypeMap: reduceProductDTypeMap
	reduceProductDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceProductGeneric[int8])
	reduceProductDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceProductGeneric[int16])
	reduceProductDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceProductGeneric[int32])
	reduceProductDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceProductGeneric[int64])
	reduceProductDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceProductGeneric[uint8])
	reduceProductDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceProductGeneric[uint16])
	reduceProductDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceProductGeneric[uint32])
	reduceProductDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceProductGeneric[uint64])
	reduceProductDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execReduceProductGeneric[float32])
	reduceProductDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execReduceProductGeneric[float64])

	// DTypeMap: reduceSumDTypeMap
	reduceSumDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execReduceSumGeneric[int8])
	reduceSumDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execReduceSumGeneric[int16])
	reduceSumDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execReduceSumGeneric[int32])
	reduceSumDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execReduceSumGeneric[int64])
	reduceSumDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execReduceSumGeneric[uint8])
	reduceSumDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execReduceSumGeneric[uint16])
	reduceSumDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execReduceSumGeneric[uint32])
	reduceSumDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execReduceSumGeneric[uint64])
	reduceSumDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execReduceSumGeneric[float32])
	reduceSumDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execReduceSumGeneric[float64])

	// DTypeMap: shiftLeftDTypeMap
	shiftLeftDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, shiftLeftGeneric[int8])
	shiftLeftDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, shiftLeftGeneric[int16])
	shiftLeftDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, shiftLeftGeneric[int32])
	shiftLeftDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, shiftLeftGeneric[int64])
	shiftLeftDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, shiftLeftGeneric[uint8])
	shiftLeftDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, shiftLeftGeneric[uint16])
	shiftLeftDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, shiftLeftGeneric[uint32])
	shiftLeftDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, shiftLeftGeneric[uint64])

	// DTypeMap: shiftRightArithmeticDTypeMap
	shiftRightArithmeticDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[int8])
	shiftRightArithmeticDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[int16])
	shiftRightArithmeticDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[int32])
	shiftRightArithmeticDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[int64])
	shiftRightArithmeticDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[uint8])
	shiftRightArithmeticDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[uint16])
	shiftRightArithmeticDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[uint32])
	shiftRightArithmeticDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, shiftRightArithmeticGeneric[uint64])

	// DTypeMap: shiftRightLogicalDTypeMap
	shiftRightLogicalDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, shiftRightLogicalGeneric[int8])
	shiftRightLogicalDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, shiftRightLogicalGeneric[int16])
	shiftRightLogicalDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, shiftRightLogicalGeneric[int32])
	shiftRightLogicalDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, shiftRightLogicalGeneric[int64])
	shiftRightLogicalDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, shiftRightLogicalGeneric[uint8])
	shiftRightLogicalDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, shiftRightLogicalGeneric[uint16])
	shiftRightLogicalDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, shiftRightLogicalGeneric[uint32])
	shiftRightLogicalDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, shiftRightLogicalGeneric[uint64])

	// DTypeMap: TransposeDTypeMap
	TransposeDTypeMap.Register(dtypes.Int8, gobackend.PriorityGeneric, execTransposeGeneric[int8])
	TransposeDTypeMap.Register(dtypes.Int16, gobackend.PriorityGeneric, execTransposeGeneric[int16])
	TransposeDTypeMap.Register(dtypes.Int32, gobackend.PriorityGeneric, execTransposeGeneric[int32])
	TransposeDTypeMap.Register(dtypes.Int64, gobackend.PriorityGeneric, execTransposeGeneric[int64])
	TransposeDTypeMap.Register(dtypes.Uint8, gobackend.PriorityGeneric, execTransposeGeneric[uint8])
	TransposeDTypeMap.Register(dtypes.Uint16, gobackend.PriorityGeneric, execTransposeGeneric[uint16])
	TransposeDTypeMap.Register(dtypes.Uint32, gobackend.PriorityGeneric, execTransposeGeneric[uint32])
	TransposeDTypeMap.Register(dtypes.Uint64, gobackend.PriorityGeneric, execTransposeGeneric[uint64])
	TransposeDTypeMap.Register(dtypes.Float32, gobackend.PriorityGeneric, execTransposeGeneric[float32])
	TransposeDTypeMap.Register(dtypes.Float64, gobackend.PriorityGeneric, execTransposeGeneric[float64])
	TransposeDTypeMap.Register(dtypes.BFloat16, gobackend.PriorityGeneric, execTransposeGeneric[bfloat16.BFloat16])
	TransposeDTypeMap.Register(dtypes.Float16, gobackend.PriorityGeneric, execTransposeGeneric[float16.Float16])
	TransposeDTypeMap.Register(dtypes.Bool, gobackend.PriorityGeneric, execTransposeGeneric[bool])

}
