/***** File generated by ./internal/cmd/gobackend_dtypemap. Don't edit it directly. *****/

package fusedops

import (
	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/dtypes/bfloat16"
	"github.com/gomlx/compute/dtypes/float16"
	"github.com/gomlx/compute/internal/gobackend"
)

func init() {

}
